version: "3.8"

services:
  backend:
    build:
      context: ./api
    container_name: gordox_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${POSTGRES_PASSWORD}@db:5432/gordox
      - REACT_APP_API_USERNAME=${REACT_APP_API_USERNAME}
      - REACT_APP_API_PASSWORD=${REACT_APP_API_PASSWORD}
    depends_on:
      - db

  frontend:
    build:
      context: ./front
    container_name: gordox_front
    ports:
      - "3001:3000"
    depends_on:
      - backend
    environment:
      - API_URL=${API_URL} 
      - REACT_APP_API_USERNAME=${REACT_APP_API_USERNAME}
      - REACT_APP_API_PASSWORD=${REACT_APP_API_PASSWORD}
  
  db:
    image: postgres:15
    container_name: gordox_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: gordox
    ports:
      - "5432:5432"
