version: "3.8"

services:
  backend:
    build:
      context: ./api
    container_name: gordox_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}

  frontend:
    build:
      context: ./front
    container_name: gordox_front
    ports:
      - "3001:3000"
    depends_on:
      - backend
